### ISSUE TITLE
items are overlapping

### ISSUE THREAD

**Issue by royjosefsson** [justin-chu/react-fast-marquee#23]
### Description

After refreshing the site and leaving the site on for some time, i noticed that items start overlapping.

---

### To Reproduce

Refresh the browser and wait for 30 minutes.
After this time the items should start overlapping.

---

### Expected behavior

Items shouldn't decrease margins after some time

---

### Screenshots

[See image](https://drive.google.com/file/d/1dL9NQxlNZe0BBn9WRZTlzkrwrHIzd0tA/view?usp=sharing)

---

System information
OS: [Linux Ubuntu 20.04]
Browser [safari]
Version: 
- react-fast-marquee: 1.2.1
- node: 14.15.2
- npm: 7.15.1

**Comment by justin-chu** [comment]
Fixed in 1.4.0

**Comment by royjosefsson** [comment]
Great job!

**Comment by ThomCM** [comment]
Please note that the issue of items overlapping was still occurring with the below snippet. It was intermittent and seemed to be mainly happening on iPhones (our tests were on the iPhone 13 & 14, pro and non-pro) but we did not have to wait 30 minutes for it - it was happening immediately. We have not tested it waiting that long.

We were showing a marquee of images like the OP and having what appears to be an identical issue - some images were travelling at a faster pace leading to overlapping. It looks like `loading="lazy"` contributed to the likelihood of this bug occurring as removing it has reduced incidents.

```
<Marquee>
       {partners.map((partner, index) => (
                    <div key={`partner${index}`} className="px-3 md:px-6">
                        <img
                            className="max-h-[60px] md:max-h-[84px] xl:max-h-[120px]"
                            src={`${assetUrl}/partners/${partner.src}`}
                            alt={partner.alt}
                            loading="lazy"
                        />
                    </div>
      ))}
</Marquee>
```


```
"react": "18.2.0",
"react-fast-marquee": "^1.5.2",
```
